# Generated by Django 2.2.5 on 2021-06-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avartar',
            field=models.ImageField(blank=True, upload_to='avartars'),
        ),
    ]
